#!/usr/bin/env python3
"""Generate the public story from a local delivered-package manifest.
No native models, STLs, private paths, reference photos or conversations are copied.
"""
import argparse, hashlib, html, json
from pathlib import Path
p=argparse.ArgumentParser(); p.add_argument('--source',type=Path,required=True); p.add_argument('--out',type=Path,required=True); a=p.parse_args()
m=json.loads((a.source/'manifest.json').read_text()); assert m['status']=='DIGITAL_PRINT_TEST_CANDIDATE_NOT_PHYSICALLY_QUALIFIED'
configs=m['configurations']; assert [c['part_count'] for c in configs]==[32,45,68]
a.out.mkdir(parents=True,exist_ok=True)
receipt={'status':m['status'],'scope':'Public story only; geometry and derived media withheld pending rights clarification.', 'configurations':[{k:c[k] for k in ('configuration','part_count','overall_dims_mm','sha256','gate_source_sha256','unchecked_count')} for c in configs], 'source_manifest_sha256':hashlib.sha256((a.source/'manifest.json').read_bytes()).hexdigest(), 'physical_samples':0,'media_source_sha256':'e304e327b70a2eec93431ab5afe39a675b95282ad46689606324d60c1557a337','geometry_downloads':'WITHHELD — reference-design redistribution license unverified','reference':{'creator':'SMACKMAX_ (@SMACKMAX)','title':'NODESTACK // SERVICE PACK','url':'https://www.printables.com/model/1837797-nodestack-service-pack','redistribution_license':'UNVERIFIED'}}
(a.out/'evidence-summary.json').write_text(json.dumps(receipt,indent=2)+'\n')
root='https://jangtrinh.github.io/design-os-3d-blender/'
repo='https://github.com/jangtrinh/design-os-3d-blender'
faqs=[('What is Nodestack?', 'This project studies a modular desk-storage system with drawer and shelf bays, raised feet, top plates and serviceable connections. The reference design is NODESTACK // SERVICE PACK by SMACKMAX_ on Printables.'),('How did OpenAI Dots and Antigravity contribute?', 'OpenAI Dots coordinated Antigravity planning and building, followed by separate evidence-based reviews. Blender native assets and rendering supported the project. Human direction and feedback shaped the requirements and revisions. This is a description of the project workflow, not an OpenAI endorsement.'),('Which configurations were checked?', 'The v16b digital print-test package contains a 2×2 canonical arrangement with 32 parts, a 2×3 tower with 45 parts and a 4×2 adjacent arrangement with 68 parts. These checks cover those three configurations, not every possible combination.'),('Is this ready for manufacturing?', 'No. Physical printing, fit, friction, strength, load capacity and stability remain unverified. The package is a digital print-test candidate, and manufacture remains blocked pending physical evidence.'),('Why are there no geometry downloads?', 'The reference-design redistribution license has not been verified. The owner chose to publish the story only and hold geometry downloads. No Blender files, STLs, reference photographs or geometry archives are distributed on this page.'),('Does the film show the v16b geometry?', 'The render source is the earlier frozen E304 base, with separately corrected modular scenes. The v16b print-test candidate improves base seating. The film is a visual explanation and does not prove the newer geometry or a physical assembly route.')]
rows=''.join('<tr><th scope="row">'+label+'</th><td>'+str(c['part_count'])+'</td><td>'+' × '.join(f'{v:.1f}' for v in c['overall_dims_mm'])+'</td></tr>' for label,c in zip(['2×2 · canonical','2×3 · tall','4×2 · adjacent'],configs))
faq=''.join('<details><summary>'+html.escape(q)+'</summary><p>'+html.escape(v)+'</p></details>' for q,v in faqs)
schema=[{'@context':'https://schema.org','@type':'SoftwareSourceCode','name':'Nodestack project story','codeRepository':repo,'url':root+'reviews/nodestack/r01/','description':'A source-backed account of Blender native prototyping and evidence review, coordinated with OpenAI Dots and Antigravity.'},{'@context':'https://schema.org','@type':'FAQPage','mainEntity':[{'@type':'Question','name':q,'acceptedAnswer':{'@type':'Answer','text':v}} for q,v in faqs]}]
base=(Path(__file__).resolve().parents[2]/'index.html').read_text(); css=base.split('<style>',1)[1].split('</style>',1)[0]
extra='''
.story-nav{display:flex;gap:16px;flex-wrap:wrap}.story-nav a{min-height:44px;display:inline-flex;align-items:center;font-size:14px}
.story-section{margin-top:80px}.story-section h2{font-size:24px;font-weight:500;letter-spacing:-.01em;margin:0 0 24px}
.story-section h3{font-size:18px;font-weight:500;margin:0 0 12px}.story-section p{max-width:68ch}
.facts{margin:32px 0;display:grid;grid-template-columns:1fr 1fr;gap:24px 32px}.facts div{min-width:0}.facts dt{font:13px var(--stack-mono);color:var(--c-gray-1100);margin-bottom:6px}.facts dd{margin:0;overflow-wrap:anywhere}
.configuration-list{list-style:none;padding:0;margin:32px 0;display:flex;flex-direction:column;gap:32px}.configuration-list li{padding:24px 0;border-top:1px solid var(--c-preview-border)}
.table-wrap{overflow-x:auto}table{border-collapse:collapse;width:100%;font-size:14px}th,td{padding:16px 8px;text-align:left;border-bottom:1px solid var(--c-preview-border)}th{font-weight:500}
.workflow{list-style:none;counter-reset:step;padding:0;margin:32px 0}.workflow li{counter-increment:step;display:grid;grid-template-columns:32px 1fr;gap:16px;margin-bottom:32px}.workflow li::before{content:counter(step);font:16px var(--stack-mono);color:var(--c-accent-text)}
.notice{border-left:2px solid var(--c-accent);padding:8px 0 8px 24px;margin:24px 0}details{border-bottom:1px solid var(--c-preview-border);padding:20px 0}summary{cursor:pointer;font-weight:500;min-height:44px;display:list-item;padding:8px 0}details p{margin:12px 0 0}
.read-links{list-style:none;padding:0}.read-links a{display:block;min-height:44px;padding:12px 0;color:var(--c-accent-text);text-decoration:underline}.story-footer{display:flex;flex-wrap:wrap;gap:24px;padding:64px 0 32px}.story-footer a{min-height:44px;display:inline-flex;align-items:center}
.hash{overflow-wrap:anywhere;font-family:var(--stack-mono);font-size:16px}.skip{position:absolute;left:16px;top:-100px}.skip:focus{top:16px;background:white;padding:12px;z-index:9}.badges img{width:auto;max-width:100%}.eyebrow.ds-heading{color:var(--c-gray-1100)}
@media(max-width:639px){.facts{grid-template-columns:1fr}.story-section{margin-top:56px}th,td{padding:12px 4px;font-size:13px}.notice{padding-left:16px}}
'''
page=f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Nodestack — modular storage, built and reviewed with evidence</title>
<meta name="description" content="Nodestack: a Blender native modular-storage study, coordinated by OpenAI Dots and Antigravity. Three digital configurations, clear physical limits.">
<link rel="canonical" href="{root}reviews/nodestack/r01/">
<meta property="og:title" content="Nodestack — modular storage, built and reviewed with evidence"><meta property="og:description" content="A project story about human-directed AI orchestration, native Blender work and bounded digital checks."><meta property="og:type" content="article"><meta property="og:url" content="{root}reviews/nodestack/r01/"><meta name="twitter:card" content="summary">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400..700&amp;family=JetBrains+Mono:wght@400;500&amp;display=swap" rel="stylesheet">
<script type="application/ld+json">{json.dumps(schema,ensure_ascii=False)}</script><style>{css}{extra}</style></head>
<body id="top"><a class="skip" href="#main">Skip to content</a><div class="ds-shell">
<nav class="ds-shell-nav" aria-label="Main navigation"><a class="wordmark" href="../../../">design:os <span>3D / Blender</span></a><div class="story-nav"><a href="#configurations">Configurations</a><a href="#workflow">How we built it</a><a href="#evidence">Evidence</a></div></nav>
<main id="main" class="ds-shell-main">
<section aria-labelledby="hero-title"><p class="eyebrow ds-heading" data-level="3">Worked build · Nodestack · project story</p><h1 id="hero-title" class="ds-heading" data-level="1">Small modules.<br>Room to grow.</h1><p class="lede">A modular desk-storage study in Blender: orange drawers, open shelves and a system explored at three scales.</p>
<div class="hero-actions"><a class="ds-btn-pill" data-tone="solid" href="#workflow">Explore the build</a><a class="text-link" href="{repo}">View the repository</a></div>
<p class="notice">Digital print-test candidate. No physical samples have been recorded; manufacture remains <strong>blocked</strong>.</p>
<dl class="facts"><div><dt>Configuration family</dt><dd>2×2 / 2×3 / 4×2</dd></div><div><dt>Digital part instances</dt><dd>{sum(c['part_count'] for c in configs)} across three checked configurations</dd></div><div><dt>Build and rendering</dt><dd>Blender native assets</dd></div><div><dt>Coordination</dt><dd>OpenAI Dots + Antigravity</dd></div><div><dt>Physical samples</dt><dd>0 recorded</dd></div><div><dt>Reference design</dt><dd>SMACKMAX_ · NODESTACK // SERVICE PACK</dd></div></dl></section>
<section id="configurations" class="story-section" aria-labelledby="config-title"><h2 id="config-title">One storage language, three arrangements</h2><p>Drawer bays keep small parts contained; shelf bays keep frequently used pieces accessible. Top plates, raised feet, links, keys and a base coupler complete the assembly.</p>
<ul class="configuration-list"><li><h3>2×2 · the starting point</h3><p>Two drawer bays and two shelf bays, arranged diagonally. The canonical package contains six drawers, their tag plates and the connecting parts.</p></li><li><h3>2×3 · more vertical storage</h3><p>Three drawer bays and three shelf bays over three tiers. Taller geometry received its own export and sampled service checks.</p></li><li><h3>4×2 · spread across the desk</h3><p>Four drawer bays and four shelf bays in adjacent clusters. The wider base and far seam remain part of the documented evidence limits.</p></li></ul>
<div class="table-wrap"><table><caption>Measured v16b assembly dimensions, in millimetres</caption><thead><tr><th scope="col">Arrangement</th><th scope="col">Parts</th><th scope="col">Width × depth × height</th></tr></thead><tbody>{rows}</tbody></table></div><p>These are measured outputs from the delivered manifest, not a load rating or proof of arbitrary stacking.</p></section>
<section id="workflow" class="story-section" aria-labelledby="workflow-title"><h2 id="workflow-title">Directed by a person. Coordinated through Dots.</h2><p>OpenAI Dots coordinated Antigravity planning and building, and separate evidence-based reviews. The workflow connected a human brief to native Blender construction, measured checks and revisions.</p><ol class="workflow"><li><div><h3>Human direction sets the target</h3><p>The owner supplied the product direction and feedback. Decisions about arrangement, appearance, mechanisms and presentation shaped subsequent revisions.</p></div></li><li><div><h3>Antigravity plans and builds</h3><p>Antigravity worked with the project scripts and Blender native assets. Models, materials, scene setup and rendering stayed traceable to saved project artifacts.</p></div></li><li><div><h3>Dots coordinates review and follow-through</h3><p>Separate reviews checked geometry, exports and sampled mechanics against their evidence. Findings led to refinements, including the v16b base-seating revision.</p></div></li></ol><p>Coordination helps keep tasks and evidence connected. It does not replace engineering judgment, human feedback or physical tests. Mention of OpenAI describes the tools used; it does not imply endorsement.</p></section>
<section id="evidence" class="story-section" aria-labelledby="evidence-title"><h2 id="evidence-title">What the digital evidence establishes</h2><p>The recorded geometry/export checks pass for 32, 45 and 68 parts. Their scope includes topology, dimensions, wall-ray screening and STL export with fresh reopen.</p><p>Sampled drawer motion covers a nominal 0–70 mm stroke. Service probes cover key removal, staged unstacking and the base route. These are bounded sampled tests, not continuous swept-volume or force/friction proofs.</p><p>The corrected retainer route slides 26 mm before dropping. The earlier 24 mm route retains a collision failure; the builder regression that misses that intermediate collision remains unresolved.</p><p>The canonical delivery scene was renamed after audit. Its identity receipt links unchanged meshes, bases and origins to the audited source; the gate does not directly carry the final delivery hash.</p><p>There are 64 / 90 / 136 unchecked entries across the three configurations: undeclared bore-feature checks and report-only overhang area. Raw seating/seam intersections and numerical-contact caveats remain documented. A sampled wall-ray screen does not establish a continuous minimum wall on every surface.</p><p><a href="evidence-summary.json">Read the public evidence summary</a></p></section>
<section class="story-section" aria-labelledby="limits-title"><h2 id="limits-title">The next step is a physical print test</h2><p>Printer, material, nozzle, shrinkage, layer adhesion, support scars, fit, friction, fatigue, strength, drawer loads and tip stability remain unverified. No rated height or payload is assigned.</p><ol class="steps"><li>Choose a real printer, material, profile and intended payload.</li><li>Print and measure small mating subsets before a complete tower.</li><li>Record fit and service results, then plan bounded load and stability tests.</li></ol><p>The default 256 mm bed and PLA/FDM 0.4 mm assumptions in the digital specifications are metadata, not validated process choices. Tag plates are geometry; film lettering is not manufactured STL lettering, and physical label attachment remains unspecified.</p></section>
<section class="story-section" aria-labelledby="media-title"><h2 id="media-title">A film explains the system; a new base improves the candidate</h2><p>The existing 30-second Full HD film uses 1,800 native rendered states at 60 fps. It is an intermediate presentation; the expanded 56-second film was still in progress when this story was prepared.</p><p>Canonical media uses frozen E304. The v16b print-test candidate changes base seating: 2.8 mm engagement, a 0.2 mm floor gap and nominal 0.4 mm lateral clearance per side. Those digital measurements do not establish fit or strength.</p><p>Exploded, catalog and blueprint views are explanatory presentation modes. Their positions and module transitions should not be read as verified physical assembly paths or authoritative manufacturing drawings.</p><p class="notice">This story distributes no reference photographs, Blender files, STLs or geometry archives. Derived renders are also held while reference-design redistribution rights remain unverified.</p></section>
<section class="story-section" aria-labelledby="reference-title"><h2 id="reference-title">Reference and provenance</h2><p>The reference design is <a href="https://www.printables.com/model/1837797-nodestack-service-pack">NODESTACK // SERVICE PACK by SMACKMAX_ (@SMACKMAX)</a>. This project is a Blender reconstruction and local engineering study; it does not claim authorship of the original design.</p><p>The reference-design redistribution license has not been verified. The repository’s MIT software license does not establish redistribution rights for that design. Geometry downloads are held at the owner’s direction.</p><p>The public summary is derived from the delivered v16b manifest and handoff. It retains artifact hashes and scope limits while excluding private paths, internal conversations and unrelated project data.</p></section>
<section class="story-section" aria-labelledby="faq-title"><h2 id="faq-title">Questions about the project</h2>{faq}</section>
<section id="ecosystem" class="story-section" aria-labelledby="ecosystem-title"><h2 id="ecosystem-title">Built within design:os</h2><p>The Blender repository carries the build workflow, native-asset policy and evidence gates used for these studies.</p><ul class="read-links"><li><a href="../../../">Explore the Blender worked builds</a></li><li><a href="https://jangtrinh.github.io/design-os/">Explore the design:os toolkit</a></li><li><a href="{repo}/blob/main/docs/blender-ai-workflow.md">Read the Blender AI workflow</a></li><li><a href="{repo}/blob/main/docs/delivery-review-publication.md">Read the publication evidence rules</a></li></ul></section>
<footer class="story-footer"><a href="{repo}">GitHub repository</a><a href="{repo}/blob/main/LICENSE">Software license</a><a href="#top">Back to top</a></footer></main></div>
<script data-name="BMC-Widget" data-cfasync="false" src="https://cdnjs.buymeacoffee.com/1.0.0/widget.prod.min.js" data-id="jangtrinh" data-description="Support me on Buy me a coffee!" data-message="" data-color="#FF813F" data-position="Right" data-x_margin="18" data-y_margin="18"></script></body></html>'''
(a.out/'index.html').write_text(page)
print('Generated story-only page and sanitized evidence summary; no project assets copied.')
